# Generated by Django 5.1.2 on 2024-11-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["title", "created_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
