# Generated by Django 5.1.2 on 2024-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите имя контакта",
                        max_length=150,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        help_text="Введите номер телефона",
                        max_length=18,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Введите email",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Введите ваш адрес",
                        null=True,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "web_site",
                    models.CharField(
                        blank=True,
                        help_text="Введите адрес веб-сайта",
                        max_length=250,
                        null=True,
                        verbose_name="Веб-сайт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
